---
title: "ISHE R Workshop: Saturday"
author: "Lisa"
date: "24/08/2019"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse) # loads packages for data manipulation (dplyr/tidyr) and visualisation (ggplot2)
library(cowplot)  # optional, lets you make composite graphs
library(plotly)   # optional, interactive graphs
library(ggthemes) # optional, lets you change themes
```

## Load and Process Data

Write stuff about your data..

```{r}
disgust <- read_csv("https://github.com/debruine/ishe2019/raw/master/data/disgust.csv")
users <- read_csv("https://github.com/debruine/ishe2019/raw/master/data/users.csv")

data <- left_join(disgust, users, by = "user_id") %>%
  filter(sex %in% c("male", "female")) %>%
  gather(question, score, moral1:pathogen7) %>%
  separate(question, c("domain", "n"), sep = -1) %>%
  group_by(domain, user_id, sex)  %>%
  summarise(sum_score = sum(score, na.rm = FALSE)) %>%
  ungroup()
```

## Plot the data

### Histogram

```{r}
ggplot(data, aes(x = sum_score, fill = domain)) +
  geom_histogram(binwidth = 1, colour = "grey", 
                 show.legend = FALSE) +
  facet_grid(domain~sex)
```

### Density

```{r}
ggplot(data, aes(x = sum_score, 
                 colour = domain, 
                 fill = domain)) +
  geom_density(alpha = 0.5) + 
  theme_clean() +
  scale_colour_manual(values = c("dodgerblue", "darkgreen", "red")) +
  scale_fill_manual(values = c("dodgerblue", "darkgreen", "red"))
```

### Freqpoly

```{r}
ggplot(data, aes(x = sum_score, 
                 colour = domain, 
                 fill = domain)) +
  geom_freqpoly(alpha = 0.5, binwidth = 1) + 
  theme_clean() +
  scale_colour_manual(values = c("dodgerblue", "darkgreen", "red")) +
  scale_fill_manual(values = c("dodgerblue", "darkgreen", "red"))
```

### Boxplot

```{r}
ggplot(data, aes(x = domain, y = sum_score, fill = domain)) +
  geom_boxplot(show.legend = FALSE) +
  facet_grid(~sex) +
  xlab("") +
  ylab("Sum Score") +
  ggtitle("Sex Differences in Disgust")
```

### Violinbox

```{r}
ggplot(data, aes(x = domain, y = sum_score, fill = domain)) +
  geom_violin(show.legend = FALSE, fill = "white") + 
  geom_boxplot(show.legend = FALSE, width = .2) +
  facet_grid(~sex) +
  xlab("") +
  ylab("Sum Score") +
  ggtitle("Sex Differences in Disgust")
```

### Point/Scatter

```{r}
data_wide <- spread(data, domain, sum_score)

p <- sample_n(data_wide, 100) %>%
  ggplot(aes(x = moral, y = sexual, colour = sex)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE)

ggplotly(p)
```

### Line Graphs

```{r}
data_wide %>%
  ggplot(aes(x = moral, y = sexual, colour = sex)) +
  geom_point(alpha = 0.05) +
  geom_smooth(method = lm, se = TRUE)
```


### Heatmaps

```{r}
ggplot(data_wide, aes(x = pathogen, y = sexual)) +
  geom_bin2d(binwidth = 1, drop = FALSE) +
  scale_fill_viridis_c()
```

### Combo plots

```{r}
pathogen_sex_plot <- ggplot(data_wide, 
                            aes(x = pathogen, y = sexual)) +
  geom_smooth(method = lm)

pathogen_moral_plot <- ggplot(data_wide, 
                            aes(x = pathogen, y = moral)) +
  geom_smooth(method = lm)

plot_grid(pathogen_sex_plot, pathogen_moral_plot)

```


### Interactive plots

```{r}

```


